# Generated by Django 5.1.5 on 2025-01-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glocal.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('domicilio_oficina', models.CharField(max_length=100)),
                ('url_web', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glocal.matriz')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glocal.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glocal.pais')),
            ],
        ),
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('changes', models.JSONField()),
                ('approved', models.BooleanField(null=True)),
                ('action_type', models.CharField(choices=[('edit', 'Edición'), ('delete', 'Eliminación')], default='edit', max_length=10)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
