# Generated by Django 5.1.5 on 2025-01-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingchange',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
