# Generated by Django 5.1.5 on 2025-02-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glocal.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='matriz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='glocal.matriz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seguroaccidentepersonal',
            name='cobertura',
            field=models.CharField(choices=[('muerte-incapacidad', 'Muerte e incapacidad'), ('asistencia-medica-farmaceutica', 'Asistencia médica / farmacéutica')], max_length=55),
        ),
    ]
