# Generated by Django 5.1.5 on 2025-02-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguro',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='limite_asegurado',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='prima_neta_emitida',
        ),
        migrations.AddField(
            model_name='archivo',
            name='url_firmada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seguroaccidentepersonal',
            name='cobertura',
            field=models.CharField(choices=[('asistencia-medica-farmaceutica', 'Asistencia médica / farmacéutica'), ('muerte-incapacidad', 'Muerte e incapacidad')], max_length=55),
        ),
    ]
