# Generated by Django 5.1.5 on 2025-01-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0002_pendingchange_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingchange',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
