# Generated by Django 5.1.5 on 2025-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0002_archivo_empresa_archivo_matriz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguroaccidentepersonal',
            name='cobertura',
            field=models.CharField(choices=[('asistencia-medica-farmaceutica', 'Asistencia médica / farmacéutica'), ('muerte-incapacidad', 'Muerte e incapacidad')], max_length=55),
        ),
    ]
