# Generated by Django 5.1.5 on 2025-01-17 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0003_alter_pendingchange_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='contactos',
            field=models.ManyToManyField(related_name='aseguradora', to='glocal.contacto'),
        ),
        migrations.AddField(
            model_name='broker',
            name='contactos',
            field=models.ManyToManyField(related_name='broker', to='glocal.contacto'),
        ),
        migrations.AddField(
            model_name='matriz',
            name='contactos',
            field=models.ManyToManyField(related_name='matrices', to='glocal.contacto'),
        ),
    ]
