# Generated by Django 5.1.5 on 2025-01-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0004_contacto_aseguradora_contactos_broker_contactos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingchange',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
