# Generated by Django 5.1.5 on 2025-01-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0005_alter_pendingchange_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingchange',
            name='action_type',
            field=models.CharField(choices=[('edit', 'Edición'), ('delete', 'Eliminación'), ('create', 'Creación')], default='edit', max_length=10),
        ),
    ]
