# Generated by Django 5.1.5 on 2025-01-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0008_categoria_aseguradora_modified_by_broker_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriz',
            name='contactos',
        ),
    ]
