# Generated by Django 5.1.5 on 2025-01-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0010_contacto_modified_by_alter_contacto_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='logo',
            field=models.ImageField(default='logo.jpg', upload_to='logos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contactos',
            field=models.ManyToManyField(related_name='empresa', to='glocal.contacto'),
        ),
    ]
