# Generated by Django 5.1.5 on 2025-01-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0011_aseguradora_logo_alter_empresa_contactos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='tax_id',
            new_name='ruc_nit',
        ),
    ]
