# Generated by Django 5.1.5 on 2025-01-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0012_rename_tax_id_empresa_ruc_nit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aseguradora',
            old_name='tax_id',
            new_name='ruc_nit',
        ),
    ]
