# Generated by Django 5.1.5 on 2025-01-30 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0014_seguro_moneda_siniestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('dni_cuil', models.CharField(max_length=100)),
                ('suma_asegurada', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguroAccidentePersonal',
            fields=[
                ('seguro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='glocal.seguro')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cobertura', models.CharField(choices=[('asistencia-medica-farmaceutica', 'Asistencia médica / farmacéutica'), ('muerte-incapacidad', 'Muerte e incapacidad')], max_length=55)),
                ('clausula_de_no_repeticion', models.CharField(max_length=255)),
                ('a_favor_de', models.CharField(max_length=100)),
                ('beneficiario_preferente', models.CharField(max_length=100)),
            ],
            bases=('glocal.seguro',),
        ),
        migrations.CreateModel(
            name='SeguroResponsabilidadCivil',
            fields=[
                ('seguro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='glocal.seguro')),
                ('cobertura', models.CharField(max_length=100)),
                ('limite', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('adicionales', models.BooleanField(default=False)),
            ],
            bases=('glocal.seguro',),
        ),
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(default='some.pdf', upload_to='archivos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seguro',
            name='tipo_seguro',
            field=models.CharField(choices=[('casualty-3b', 'CASUALTY - 3B'), ('casualty-dyo', 'CASUALTY - D&O'), ('casualty-rc_l', 'CASUALTY - RESPONSABILIDAD CIVIL / LIABILITY'), ('casualty-rc_p', 'CASUALTY - RESPONSABILIDAD CIVIL DE PRODUCTOS'), ('casualty-rc_r', 'CASUALTY - RESPONSABILIDAD CIVIL DE RECALL'), ('casualty-rc_p_eyo', 'CASUALTY - RESPONSABILIDAD CIVIL DE PROFESIONAL (E&O)'), ('casualty-r_f', 'CASUALTY - ROBO / FIDELITY'), ('otros-cyber-risk', 'OTROS - CYBER RISK'), ('otros-vehiculos', 'OTROS - VEHICULOS'), ('property-cascos_hull', 'PROPOERTY - CASCOS / HULL'), ('property-multiriesgo_prop', 'PROPERTY - MULTIRIESGO / PROPERTY'), ('transporte-expo', 'TRANSPORTE (EXPO)'), ('transporte-impo', 'TRANSPORTE (IMPO)'), ('accidentes-personales', 'ACCIDENTES PERSONALES')], max_length=25),
        ),
    ]
