# Generated by Django 5.1.5 on 2025-01-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glocal', '0015_nomina_seguroaccidentepersonal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguroaccidentepersonal',
            name='cobertura',
            field=models.CharField(choices=[('muerte-incapacidad', 'Muerte e incapacidad'), ('asistencia-medica-farmaceutica', 'Asistencia médica / farmacéutica')], max_length=55),
        ),
    ]
